name: straw_mcp
description: A Dart implementation of the Model Context Protocol (MCP), enabling seamless integration between Dart/Flutter applications and LLM services.
version: 0.5.0
repository: https://github.com/szktty/straw-mcp

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  path: ^1.8.0
  synchronized: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
